import json
import os

from groq import Groq

from services.llm_service import DEFAULT_GROQ_MODEL


def _parse_dishes(content: str) -> list[dict]:
    """Handle JSON mode and tolerate harmless provider formatting around it."""
    content = (content or "").strip()
    candidates = [content]
    first_brace, last_brace = content.find("{"), content.rfind("}")
    if first_brace != -1 and last_brace > first_brace:
        candidates.append(content[first_brace : last_brace + 1])
    for candidate in candidates:
        try:
            dishes = json.loads(candidate).get("dishes", [])
            if isinstance(dishes, list):
                return dishes
        except (json.JSONDecodeError, AttributeError):
            continue
    raise ValueError("AI returned an unreadable recipe response. Please try again.")


def suggest_foods(state: str, meal_type: str, language: str) -> list[dict]:
    """Return several regional, usable recipes generated by the configured AI."""
    key = os.getenv("GROQ_API_KEY", "").strip()
    model = os.getenv("GROQ_MODEL", DEFAULT_GROQ_MODEL).strip() or DEFAULT_GROQ_MODEL
    if not key:
        raise ValueError("AI is not configured. Add GROQ_API_KEY in backend/.env.")

    prompt = f"""Suggest exactly 5 practical {meal_type} dishes appropriate for {state}, India.
Write dish names, descriptions, ingredients, and short numbered instructions in {language}.
Return JSON only in this exact shape:
{{"dishes":[{{"dish_name":"...","description":"...","ingredients":["..."],"instructions":["..."]}}]}}
Use real, safe recipes. Do not include markdown or commentary outside the JSON."""
    client = Groq(api_key=key)
    request = {
        "model": model,
        "messages": [{"role": "system", "content": "You are a precise Indian home-cooking planner. Return valid JSON only."}, {"role": "user", "content": prompt}],
        "temperature": 0.35,
    }
    try:
        # JSON mode is preferred, but some hosted models reject their own JSON
        # before returning it. The retry below keeps the feature available.
        response = client.chat.completions.create(**request, response_format={"type": "json_object"})
    except Exception:
        response = client.chat.completions.create(**request)
    dishes = _parse_dishes(response.choices[0].message.content or "")
    if not isinstance(dishes, list) or not dishes:
        raise ValueError("AI could not generate food ideas. Please try again.")
    clean = []
    for index, dish in enumerate(dishes[:5]):
        if not all(dish.get(field) for field in ("dish_name", "description", "ingredients", "instructions")):
            continue
        ingredients = dish["ingredients"] if isinstance(dish["ingredients"], list) else [item.strip() for item in str(dish["ingredients"]).split(",") if item.strip()]
        instructions = dish["instructions"] if isinstance(dish["instructions"], list) else [item.strip() for item in str(dish["instructions"]).split("\n") if item.strip()]
        clean.append({"id": f"ai-{index}", **dish, "ingredients": ingredients, "instructions": instructions})
    if not clean:
        raise ValueError("AI could not generate complete recipes. Please try again.")
    return clean
