import { createContext, useContext, useEffect, useState } from "react";
import { getProfile } from "./api";
const copy = {
  English: { brandTagline: "Your calm home command center", dashboard: "Dashboard", assistant: "AI Assistant", food: "Food ideas", tasks: "Tasks", profile: "Profile", welcome: "Good to see you", dashboardIntro: "Here is a thoughtful view of your home, plans and kitchen.", today: "Today at home", weather: "Weather", activeTasks: "Active tasks", dinnerIdeas: "Ideas for dinner", askAssistant: "Ask your home assistant", viewAll: "View all", noTasks: "Nothing needs your attention right now.", loading: "Loading your dashboard...", save: "Save changes", profileTitle: "Your profile", profileIntro: "Keep your home preferences in one private place.", name: "Name", state: "State", city: "City", language: "Language", saved: "Profile saved" },
  Tamil: { brandTagline: "உங்கள் வீட்டின் கட்டுப்பாட்டு மையம்", dashboard: "முகப்பு", assistant: "AI உதவியாளர்", food: "உணவு யோசனைகள்", tasks: "பணிகள்", profile: "சுயவிவரம்", welcome: "மீண்டும் சந்திப்பதில் மகிழ்ச்சி", dashboardIntro: "உங்கள் வீடு, திட்டங்கள் மற்றும் சமையலறையின் பார்வை.", today: "இன்றைய வீடு", weather: "வானிலை", activeTasks: "செயலில் உள்ள பணிகள்", dinnerIdeas: "இரவு உணவு யோசனைகள்", askAssistant: "வீட்டு உதவியாளரிடம் கேளுங்கள்", viewAll: "அனைத்தையும் காண்க", noTasks: "இப்போது கவனிக்க வேண்டிய பணிகள் இல்லை.", loading: "முகப்பு ஏற்றப்படுகிறது...", save: "மாற்றங்களை சேமி", profileTitle: "உங்கள் சுயவிவரம்", profileIntro: "உங்கள் விருப்பங்களை ஒரே தனிப்பட்ட இடத்தில் வையுங்கள்.", name: "பெயர்", state: "மாநிலம்", city: "நகரம்", language: "மொழி", saved: "சுயவிவரம் சேமிக்கப்பட்டது" },
  Hindi: { brandTagline: "आपके घर का स्मार्ट डैशबोर्ड", dashboard: "डैशबोर्ड", assistant: "AI सहायक", food: "खाने के विचार", tasks: "काम", profile: "प्रोफ़ाइल", welcome: "फिर मिलकर अच्छा लगा", dashboardIntro: "घर, योजनाओं और रसोई की एक स्पष्ट झलक।", today: "आज घर पर", weather: "मौसम", activeTasks: "सक्रिय काम", dinnerIdeas: "रात के खाने के विचार", askAssistant: "होम असिस्टेंट से पूछें", viewAll: "सभी देखें", noTasks: "अभी आपका कोई काम बाकी नहीं है।", loading: "डैशबोर्ड लोड हो रहा है...", save: "बदलाव सहेजें", profileTitle: "आपकी प्रोफ़ाइल", profileIntro: "अपनी घरेलू प्राथमिकताएँ एक निजी जगह पर रखें।", name: "नाम", state: "राज्य", city: "शहर", language: "भाषा", saved: "प्रोफ़ाइल सहेजी गई" },
};
const Context = createContext({ language: "English", t: (key) => key, refreshLanguage: () => {} });
export function LanguageProvider({ children }) { const [language, setLanguage] = useState(localStorage.getItem("home-language") || "English"); useEffect(() => { getProfile().then((p) => setLanguage(p.language || "English")).catch(() => {}); }, []); useEffect(() => { localStorage.setItem("home-language", language); document.documentElement.lang = language === "Tamil" ? "ta" : language === "Hindi" ? "hi" : "en"; }, [language]); const t = (key) => (copy[language] || copy.English)[key] || copy.English[key] || key; return <Context.Provider value={{ language, t, refreshLanguage: setLanguage }}>{children}</Context.Provider>; }
export const useLanguage = () => useContext(Context);
